package bank_classes;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Account.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//




public class Account {
	public String account_code;
	public Number initial_balance;
	public Number get_balance() {
	
	}
	
	public History get_history() {
	
	}
	
	public Transaction add_to_history(Object Transaction t) {
	
	}
	
	public String get_branch_code() {
	
	}
}
