package bank_classes;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bank.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class Bank {
	private int account_number;

	public Branch get_branch(String branch_code) {

	}

	public Client get_client(String client_username, String branch_id) {

	}

	public Clerk get_clerk(String clerk_username, String branch_id) {

	}

	public String next_account_number() {

	}
}
