package bank_classes;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class Client extends User {
	private String cpf;

	public Account get_account() {

	}
}
