package bank_classes;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Deposit.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class Deposit extends Transaction {
	public String cashParcelCode;
}
