package bank_classes;
import java.util.*;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : History.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//




public class History {
	
	public History(){
		List<Withdrawal> list_withdraw = new ArrayList<Withdrawal>(50);
		List<Deposit> list_deposit = new ArrayList<Deposit>(50);
		List<Transaction> list_transaction = new ArrayList<Transaction>(50);
	}
	public Money sum_transaction_values() {
	      Money sum = new money;
	      for(Withdrawal element, list_withdraw){	    	  
	    	  sum=element.add(sum);
	      }
	      for(Deposit element : list_deposit){
	    	  sum=element.add(sum)
	      }
	      for(Transaction element : list_transaction){
	          money=element.add(sum)
	      }
		return sum;
	}
	
	public void store_transaction(Transaction t) {
		if(t instanceof Withdrawal){
			list_withdraw.add(1,t);
		}
		else if(t instanceof Deposit){
			list_deposit.add(1,t);
		}
		else 
			list_transaction.add(1,t);
	}
	
	public Transfer[] get_all_transfers() {
	       return list_transaction;
	}
	
	public Withdrawal[] get_all_withdrawals() {
	       return list_withdraw;
	}
	
	public Deposit[] get_all_deposits() {
		   return list_deposit
	}
	
	public History get_transactions(Date from, Date to) {
	
	}
}
