package bank_classes;
import java.util.Calendar;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Bank System
//  @ File Name : User.java
//  @ Date : 01/06/2013
//  @ Authors : Pablo, Matheus , Leonardo Silveira Ponzoni 
//
//

public class User {
	private String name,
				   surname;
	private Calendar birthday;
	private String username,
				   password;

	public boolean passwordMatch(String password) {
		return this.password.equals(password);
	}

	public boolean usernameMatch(String username) {
		return this.username.equals(username);
	}
	
	public User(String name,String surname,Calendar birthday,String username, String password){
		this.name = name;
		this.surname = surname;
		this.birthday = birthday;
		this.username = username;
		this.password = password;
	}
	
	public String toString(){
		return String.format("Name: %s\n Surname: %s\n Birthday: %s\n User:%s Password:%s ",
					name,
					surname,
					birthday.toString(),
					username,
					password);
	}
}
