package bank_classes;
import java.util.Calendar;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class User {
	private String name;
	private String surname;
	private String password;
	private String username;
	private Calendar birthday;

	public boolean passwordMatch(String password) {
		return false;
	}

	public boolean usernameMatch(String username) {
		return (this.username).equals(username);
	}
	
	public User(String name,String surname,Calendar birthday,String username, String password){
		this.name = name;
		this.surname = surname;
		this.birthday = birthday;
		this.username = username;
		this.password = password;
	}
}
