package bank_classes;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Withdrawal.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//

public class Withdrawal extends Transaction {
	
	public Withdrawal(String location_access_branch_code, Date date, Number value, String this_acc_code){
		super(location_access_branch_code, date, value, this_acc_code)
	}
	    
	public Number get_value() {
        return -value;
	}
}
