//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Branch.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//




public class Branch {
	private String code;
	private Collection<Clerk> branch_clerks;
	private Collection<Client> branch_accounts;
	private String name;
	public Clerk get_clerk(String username) {
	
	}
	
	public Clerk get_clerk(int clerk_id) {
	
	}
	
	public Client get_client(String username) {
	
	}
	
	public String get_name() {
	
	}
	
	public String get_code() {
	
	}
	
	public String code_match(String branch_code) {
	
	}
	
	public boolean has_account(String client) {
	
	}
	
	public void add_client(Client client) {
	
	}
	
	public boolean works_here(String clerk) {
	
	}
}
