//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Clerk.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//




public class Clerk extends User{
}
