//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Transaction.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//




public class Transaction {
	private String access_branch_code;
	private Date date;
	private Number value;
	private String this_acc_code;
	public Number get_value() {
	
	}
	
	public Date get_date() {
	
	}
	
	public boolean newer_than(Date time) {
	
	}
	
	public boolean older_than(Date time) {
	
	}
	
	public boolean in_time_period(Date from, Date to) {
	
	}
}
