//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Transfer.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//




public class Transfer extends Transaction {
	public String to_accound_code;
	public String to_branch_code;
	public String from_account_code;
	public String from_branch_code;
	public Account get_from() {
	
	}
	
	public Account get_to() {
	
	}
	
	public Number get_value() {
	
	}
	
	public void Transfer(Account from, Account to, int Value) {
	
	}
}
