//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UI.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//




public class UI {
	private boolean logged_in;
	public User current_user;
	public Branch access_branch;
	public String login(String username, String branch, String password) {
	
	}
	
	public String logout() {
	
	}
	
	private void disable_operations() {
	
	}
	
	public boolean isLoggedIn?() {
	
	}
	
	private String enable_financial_functions() {
	
	}
	
	public String deposit(Number ammount, String cashParcelId, Client holder) {
	
	}
	
	public String withdraw(Number ammount, Client holder) {
	
	}
	
	public String transfer(Number ammount, Client from, Client to) {
	
	}
	
	private void get_period_from_user() {
	
	}
	
	public void get_month_from_user() {
	
	}
	
	private String transaction_history(Client holder, Date from, Date to) {
	
	}
	
	private String transaction_history(Client holder, MonthOptionEnum month) {
	
	}
	
	public String transaction_history_to_print(Client holder, TimeOptionEnum statement_type) {
	
	}
	
	public String balance(Client holder) {
	
	}
}
