//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//




public class User {
	private String name;
	private String surname;
	private String password;
	private String username;
	private Calendar birthday;
	public boolean passwordMatch(String password) {
	
	}
	
	public boolean usernameMatch(String username) {
	
	}
}
