//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Withdrawal.java
//  @ Date : 01/06/2013
//  @ Author : 
//
//




public class Withdrawal extends Transaction{
}
